### ISSUE TITLE
Set root URL for the module

### ISSUE THREAD

**Issue by jmalczyk** [MapofLife/inventory-module#1]
Everything this module serves needs to be accessible via the same endpoint ... so URL's like /client/ wont work. It should be possible to set up the app to serve everything from /<module>/  using
https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.modules.modules#google.appengine.api.modules.modules.get_current_module_name in the template and some magic in app.yaml

**Comment by rafelafrance** [comment]
Changed back
